site_name: Morphux Developer Documentation
pages:
    - Home: index.md
    - Packages: Package.md
    - Infrastructure: Infrastructure.md
    - Installer: Installer.md
theme: null
theme_dir: theme
repo_url: https://github.com/Morphux/Developer-Documentation
